services:
  owrx:
    image: 'slechev/openwebrxplus-softmbe:latest'
    container_name: owrx-mbe
    restart: unless-stopped
    ports:
      - '8073:8073'
    environment:
      TZ: Europe/Sofia
      OPENWEBRX_ADMIN_USER: locutus
      OPENWEBRX_ADMIN_PASSWORD: n3ur0manc3r
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /opt/owrx-docker/etc:/etc/openwebrx
      - /opt/owrx-docker/var:/var/lib/openwebrx
      - /opt/owrx-docker/plugins:/usr/lib/python3/dist-packages/htdocs/plugins
    # mount /tmp in memory, for RPi devices, to avoid SD card wear and make dump1090 work faster
    tmpfs:
      - /tmp:mode=1777
