http_base_url: http://signals.local

pid_file_location: ""

services:
    icecase:
        system_ctl_name: icecast2.service
        type: systemd
        description: Icecast
        link: http://signals.local:8000
        configmethod: null          # no config method defined
        current_status: null
        autostart: false
        require_sdr: false
    # darkice:
    #     system_ctl_name: darkice.service
    #     type: systemd
    #     description: Darkice
    #     link: null
    #     configmethod: null          # no config method defined
    #     current_status: false
    #     autostart: false
    #     require_sdr: false
    kismet:
        system_ctl_name: kismet.service
        type: systemd
        description: Kismet
        link: http://signals.local:2501
        configmethod: null          # no config method defined
        current_status: null
        autostart: false
        require_sdr: false
    openwebex:
        type: docker
        container_name: owrx-mbe
        description: "Openwebex+"
        link: "http://signals.local:8073"
        configmethod: null
        current_status: null
        autostart: false
        default_sdr: '77771111153705700'
        selected_sdr: '77771111153705700'
        require_sdr: true
    pagermon_server:
        type: docker
        container_name: pagermon
        description: Pagermon Server
        cmd_line: ""
        working_dir: "/opt/pagermon"
        autostart: false
        current_status: null
        require_sdr: false
        link: "http://signals.local:3000/"
    pagermon_client1:
        type: cli
        description: Pagermon Client
        cmd_line: "/opt/pagermon/client/reader_alt.sh 1 152.592M"
        working_dir: /opt/pagermon/client
        autostart: false
        current_status: null
        require_sdr: true
        freq_input: "152.592M"
        default_sdr: null
        selected_sdr: null
        link: null
    pagermon_client2:
        type: cli
        description: Pagermon Client
        cmd_line: "/opt/signals_box_ctl/pagermon_client.sh 2 929.612M"
        working_dir: /opt/pagermon/client
        autostart: false
        current_status: null
        default_sdr: null
        selected_sdr: null
        require_sdr: true
        freq_input: "929.612M"
        link: null

buttons:
  - name: "refresh_page" 
    text: "Refresh Page"
    html_command: "onClick=\"window.location.reload();\""
  - name: "reload_config" 
    text: "Reload Config"
    html_command: "type=\"submit\""
  - name: "shutdown" 
    text: "Shutdown"
    html_command: "type=\"submit\""
    cli_command: ["/usr/sbin/shutdown", "now"]
  - name: "reboot" 
    text: "Reboot"
    html_command: "type=\"submit\""
    cli_command: ["/usr/sbin/reboot"]

links:
  - id: vnc
    url: "vnc://signals.local:5901"
    name: VNC Access
  # - id: rdp
  #   url: "rdp://signals.local"
  #   name: RDP Access
