services:
  recorder:
    image: robotastic/trunk-recorder:latest
    container_name: trunk-recorder
    restart: always
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb:rwm"
    volumes:
      - /var/run/dbus:/var/run/dbus 
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ./config:/app
  player: 
    container_name: player
    environment: 
      - TZ=America/New_York
    image: docker.io/chuot/rdio-scanner:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data:z