services:
  intercept-tool:
    build: .
    container_name: intercept_local
    network_mode: "host"
    privileged: true
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
      - /var/run/dbus:/var/run/dbus
      - /run/udev:/run/udev:ro       # Allows container to see host driver events
    stdin_open: true
    tty: true
